name: Clubhouse Release Plugin
description: Creates a Clubhouse release from merged in features
author: CaseyMichael
requirements: 
  - curl
  - jq
configuration:
  properties:
    CLUBHOUSE_API_TOKEN:
      type: string
    CLUBHOUSE_RELEASE_STORY_ID:
      type: number
    GITHUB_API_TOKEN:
      type: string
    GITHUB_OWNER:
      type: string
    GITHUB_REPO:
      type: string
    GITHUB_BASE_BRANCH:
      type: string
    GITHUB_RELEASE_BRANCH:
      type: string