name: Clubhouse Buildkite Status Badge Plugin
description: Creates a task with the buildkite status badge on your Clubhouse story
author: CaseyMichael
requirements: 
  - curl
  - jq
configuration:
  properties:
    CLUBHOUSE_API_TOKEN:
      type: string
    GITHUB_BRANCH_NAME:
      type: string
    BUILDKITE_PIPELINE_URL:
      type: string
    BUILDKITE_PIPELINE_BADGE_URL:
      type: string
    