name: Clubhouse Buildkite Status Badge Plugin
description: Creates a Clubhouse task with a branch specific buildkite status badge
author: https://github.com/CaseyMichael
requirements: 
  - curl
  - jq
configuration:
  properties:
    CLUBHOUSE_API_TOKEN:
      type: string
    BUILDKITE_BRANCH:
      type: string
    REPOSITORY_NAME:
      type: string
    BUILDKITE_PIPELINE_URL:
      type: string
    BUILDKITE_PIPELINE_BADGE_URL:
      type: string
    